"""
https://leetcode.com/problems/find-the-difference/
Given two strings s and t which consist of only lowercase letters.

Strings t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""


"""
Runtime: 64 ms, faster than 11.29% of Python3 online submissions for Find the Difference.
Memory Usage: 13.8 MB, less than 60.31% of Python3 online submissions for Find the Difference.
"""
class Solution:

    def sumChars(self, s: str):
        result = 0
        for c in s:
            result ^= ord(c)
        return result

    def findTheDifference(self, s: str, t: str) -> str:
        sum1 = self.sumChars(s)
        sum2 = self.sumChars(t)
        return chr(sum1 ^ sum2)


print(Solution().findTheDifference("abcd", "abcde"))  # e